language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
install:
  - "pip install -U pip"
  - "python setup.py install"
  - "pip install pytest-timeout"
jobs:
  include:
    - script: pytest
